theme: jekyll-theme-architect
title: Welcome to my Crypto-Blog
description: My goal is to keep the world informed of the wonderful pushes forward in cryptocurrency and decentralized systems. 

* The first token I want to talk about is the BasicAttentionToken
  *this token is developed on the ethereum platform as a ERC20 token integrated with the [Brave](https://brave.com/) open-source browser. 
